/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meupaint;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author bv110309
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private int xPress;
    private int yPress;
    private static int numeroDeLados = 3; // adicionado para acessar de outra classe
    
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        painelBotoes = new javax.swing.JPanel();
        btnLinha = new javax.swing.JToggleButton();
        btnRetangulo = new javax.swing.JToggleButton();
        btnElipse = new javax.swing.JToggleButton();
        btnPoligono = new javax.swing.JToggleButton();
        btnCor1 = new javax.swing.JButton();
        btnCor2 = new javax.swing.JButton();
        ladosPoligono = new javax.swing.JComboBox<>();
        painelDesenho = new meupaint.PainelDesenho();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu Paint");

        buttonGroup.add(btnLinha);
        btnLinha.setSelected(true);
        btnLinha.setText("Linha");

        buttonGroup.add(btnRetangulo);
        btnRetangulo.setText("Retângulo");

        buttonGroup.add(btnElipse);
        btnElipse.setText("Elipse");

        buttonGroup.add(btnPoligono);
        btnPoligono.setText("Poligono");
        btnPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoligonoActionPerformed(evt);
            }
        });

        btnCor1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCor1.setText("Cor 1");
        btnCor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCor1ActionPerformed(evt);
            }
        });

        btnCor2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCor2.setText("Cor 2");
        btnCor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCor2ActionPerformed(evt);
            }
        });

        ladosPoligono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "03 Lados", "04 Lados", "05 Lados", "06 Lados", "07 Lados", "08 Lados", "09 Lados", "10 Lados", "11 Lados", "12 Lados", "13 Lados", "14 Lados", "15 Lados", "16 Lados", "17 Lados", "18 Lados", "19 Lados", "20 Lados" }));
        ladosPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladosPoligonoActionPerformed(evt);
            }
        });

        painelDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseDragged(evt);
            }
        });
        painelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelDesenhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                        .addComponent(btnLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElipse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPoligono)
                        .addGap(30, 30, 30)
                        .addComponent(btnCor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCor2)
                        .addGap(18, 18, 18)
                        .addComponent(ladosPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelDesenho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRetangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLinha)
                        .addComponent(btnElipse)
                        .addComponent(btnCor1)
                        .addComponent(btnCor2)
                        .addComponent(btnPoligono)
                        .addComponent(ladosPoligono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void painelDesenhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMousePressed
        xPress = evt.getX();
        yPress = evt.getY();
    }//GEN-LAST:event_painelDesenhoMousePressed

    private void painelDesenhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseReleased
        
        Forma novaForma = null;
        
        if ( btnLinha.isSelected() ) {
            novaForma = new Linha( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground() );
        } else if ( btnRetangulo.isSelected() ) {
            novaForma = new Retangulo( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground(), btnCor2.getForeground() );
        } else if ( btnElipse.isSelected() ){
            novaForma = new Elipse( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground(), btnCor2.getForeground() );
        } else { // adiciona poligono
            novaForma = new Poligono( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground(), btnCor2.getForeground() );
        }
        
        painelDesenho.adicionarForma( novaForma );
        painelDesenho.setFormaTemporaria( null );
        painelDesenho.repaint();
        
    }//GEN-LAST:event_painelDesenhoMouseReleased

    private void painelDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseDragged
        
        Forma formaTemp = null;
        int lados = getNumeroDeLados(); // atualiza?
        
        if ( btnLinha.isSelected() ) {
            formaTemp = new Linha( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground() );
        } else if ( btnRetangulo.isSelected() ) {
            formaTemp = new Retangulo( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground(), btnCor2.getForeground() );
        } else if ( btnElipse.isSelected() ) {
            formaTemp = new Elipse( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground(), btnCor2.getForeground() );
         } else if ( btnPoligono.isSelected() ) { // adiciona poligono
            formaTemp = new Poligono( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground(), btnCor2.getForeground() );
        }
        
        
        painelDesenho.setFormaTemporaria( formaTemp );
        painelDesenho.repaint();
        
    }//GEN-LAST:event_painelDesenhoMouseDragged

    private void btnCor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCor1ActionPerformed
        
        Color c = JColorChooser.showDialog( 
                this, "Cor do Contorno", btnCor1.getForeground() );
        
        if ( c != null ) {
            btnCor1.setForeground( c );
        }
        
    }//GEN-LAST:event_btnCor1ActionPerformed

    private void btnCor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCor2ActionPerformed
        
        Color c = JColorChooser.showDialog( 
                this, "Cor do Contorno", btnCor2.getForeground() );
        
        if ( c != null ) {
            btnCor2.setForeground( c );
        }
        
    }//GEN-LAST:event_btnCor2ActionPerformed

    
    private void btnPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoligonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoligonoActionPerformed

    private void ladosPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladosPoligonoActionPerformed
        String itemSelecionado = (String) ladosPoligono.getSelectedItem();
        // Extrai apenas o número de lados
        numeroDeLados = Integer.parseInt(itemSelecionado.split(" ")[0]);
        System.out.printf("Número de lados atualizado: %d%n", numeroDeLados);
    }//GEN-LAST:event_ladosPoligonoActionPerformed
    
    public static int getNumeroDeLados() {
        return numeroDeLados;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCor1;
    private javax.swing.JButton btnCor2;
    private javax.swing.JToggleButton btnElipse;
    private javax.swing.JToggleButton btnLinha;
    private javax.swing.JToggleButton btnPoligono;
    private javax.swing.JToggleButton btnRetangulo;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> ladosPoligono;
    private javax.swing.JPanel painelBotoes;
    private meupaint.PainelDesenho painelDesenho;
    // End of variables declaration//GEN-END:variables
}
